export enum Loggers {
  'START' = 'START',
  'ERROR' = 'ERROR',
  'ERROR_GLOBAL_EXCEPTION' = 'ERROR_GLOBAL_EXCEPTION',
  'ERROR_HTTP_EXCEPTION' = 'ERROR_HTTP_EXCEPTION',
  'CONTROLLER_METHOD' = 'CONTROLLER_METHOD',
  'END' = 'END',
}
